local ReplicatedStorage = game:GetService("ReplicatedStorage")
local GuiManager = require(ReplicatedStorage:WaitForChild("GuiManager"))
local OpenCommandMenu = ReplicatedStorage:WaitForChild("OpenCommandMenu")
local StartTraining = ReplicatedStorage:WaitForChild("StartTraining")
local JoinTraining = ReplicatedStorage:WaitForChild("JoinTraining")
local HostKick = ReplicatedStorage:WaitForChild("HostKick")
local HostStartNow = ReplicatedStorage:WaitForChild("HostStartNow")
local HostCancel = ReplicatedStorage:WaitForChild("HostCancel")

OpenCommandMenu.OnClientEvent:Connect(function()
end)
StartTraining.OnClientEvent:Connect(function()
end)
JoinTraining.OnClientEvent:Connect(function()
end)
HostKick.OnClientEvent:Connect(function()
end)
HostStartNow.OnClientEvent:Connect(function()
end)
HostCancel.OnClientEvent:Connect(function()
end)